# -*- coding: utf-8 -*-

from .. import _

SMORFIA = {
    1: {"icon": "1.jpg", "name": _("Italia")},
    2: {"icon": "2.jpg", "name": _("Bambina")},
    3: {"icon": "3.jpg", "name": _("Gatta")},
    4: {"icon": "4.jpg", "name": _("Maiale")},
    5: {"icon": "5.jpg", "name": _("Mano")},
    6: {"icon": "6.jpg", "name": _("Chi va per via")},
    7: {"icon": "7.jpg", "name": _("Vaso")},
    8: {"icon": "8.jpg", "name": _("Madonna")},
    9: {"icon": "9.jpg", "name": _("Figli")},
    10: {"icon": "10.jpg", "name": _("Fave")},
    11: {"icon": "11.jpg", "name": _("Topi")},
    12: {"icon": "12.jpg", "name": _("Soldato")},
    13: {"icon": "13.jpg", "name": _("Sant'Antonio")},
    14: {"icon": "14.jpg", "name": _("Ubriaco")},
    15: {"icon": "15.jpg", "name": _("Ragazzo")},
    16: {"icon": "16.jpg", "name": _("Deretano")},
    17: {"icon": "17.jpg", "name": _("Sfortuna")},
    18: {"icon": "18.jpg", "name": _("Sangue")},
    19: {"icon": "19.jpg", "name": _("Risata")},
    20: {"icon": "20.jpg", "name": _("Festa")},
    21: {"icon": "21.jpg", "name": _("Donna nuda")},
    22: {"icon": "22.jpg", "name": _("Pazzo")},
    23: {"icon": "23.jpg", "name": _("Scemo")},
    24: {"icon": "24.jpg", "name": _("Guardia")},
    25: {"icon": "25.jpg", "name": _("Natale")},
    26: {"icon": "26.jpg", "name": _("Annuncio")},
    27: {"icon": "27.jpg", "name": _("Cantante")},
    28: {"icon": "28.jpg", "name": _("Fiasco")},
    29: {"icon": "29.jpg", "name": _("Padre dei figli")},
    30: {"icon": "30.jpg", "name": _("Pane")},
    31: {"icon": "31.jpg", "name": _("Padrone")},
    32: {"icon": "32.jpg", "name": _("Capo")},
    33: {"icon": "33.jpg", "name": _("Cristo")},
    34: {"icon": "34.jpg", "name": _("Testa")},
    35: {"icon": "35.jpg", "name": _("Uccello")},
    36: {"icon": "36.jpg", "name": _("Chitarra")},
    37: {"icon": "37.jpg", "name": _("Monaco")},
    38: {"icon": "38.jpg", "name": _("Colpi")},
    39: {"icon": "39.jpg", "name": _("Corda")},
    40: {"icon": "40.jpg", "name": _("Fune")},
    41: {"icon": "41.jpg", "name": _("Coltello")},
    42: {"icon": "42.jpg", "name": _("Caffè")},
    43: {"icon": "43.jpg", "name": _("Pranzo")},
    44: {"icon": "44.jpg", "name": _("Camera")},
    45: {"icon": "45.jpg", "name": _("Vino")},
    46: {"icon": "46.jpg", "name": _("Denaro")},
    47: {"icon": "47.jpg", "name": _("Morto")},
    48: {"icon": "48.jpg", "name": _("Morto che parla")},
    49: {"icon": "49.jpg", "name": _("Carne")},
    50: {"icon": "50.jpg", "name": _("Pane e vino")},
    51: {"icon": "51.jpg", "name": _("Ladro")},
    52: {"icon": "52.jpg", "name": _("Madre")},
    53: {"icon": "53.jpg", "name": _("Vecchia")},
    54: {"icon": "54.jpg", "name": _("Scarpa")},
    55: {"icon": "55.jpg", "name": _("Musica")},
    56: {"icon": "56.jpg", "name": _("Caduta")},
    57: {"icon": "57.jpg", "name": _("Gobbo")},
    58: {"icon": "58.jpg", "name": _("Bocca")},
    59: {"icon": "59.jpg", "name": _("Palla")},
    60: {"icon": "60.jpg", "name": _("Lamento")},
    61: {"icon": "61.jpg", "name": _("Cacciatore")},
    62: {"icon": "62.jpg", "name": _("Oste")},
    63: {"icon": "63.jpg", "name": _("Sposa")},
    64: {"icon": "64.jpg", "name": _("Fortuna")},
    65: {"icon": "65.jpg", "name": _("Pianto")},
    66: {"icon": "66.jpg", "name": _("Due gambe")},
    67: {"icon": "67.jpg", "name": _("Scatola")},
    68: {"icon": "68.jpg", "name": _("Bacio")},
    69: {"icon": "69.jpg", "name": _("Casa")},
    70: {"icon": "70.jpg", "name": _("Tempio")},
    71: {"icon": "71.jpg", "name": _("Uomo")},
    72: {"icon": "72.jpg", "name": _("Donna")},
    73: {"icon": "73.jpg", "name": _("Porta")},
    74: {"icon": "74.jpg", "name": _("Naso")},
    75: {"icon": "75.jpg", "name": _("Dito")},
    76: {"icon": "76.jpg", "name": _("Piede")},
    77: {"icon": "77.jpg", "name": _("Diavolo")},
    78: {"icon": "78.jpg", "name": _("Bello")},
    79: {"icon": "79.jpg", "name": _("Brutto")},
    80: {"icon": "80.jpg", "name": _("Bocca di rosa")},
    81: {"icon": "81.jpg", "name": _("Occhio")},
    82: {"icon": "82.jpg", "name": _("Tavola")},
    83: {"icon": "83.jpg", "name": _("Grande")},
    84: {"icon": "84.jpg", "name": _("Piccolo")},
    85: {"icon": "85.jpg", "name": _("Fratello")},
    86: {"icon": "86.jpg", "name": _("Sorella")},
    87: {"icon": "87.jpg", "name": _("Prete")},
    88: {"icon": "88.jpg", "name": _("Bambino")},
    89: {"icon": "89.jpg", "name": _("Vecchio")},
    90: {"icon": "90.jpg", "name": _("Paura")}
}